### ISSUE TITLE
There is no implementation of 'isDateInToday'

### ISSUE THREAD

**Issue by kamilpowalowski** [harlanhaskins/Punctual.swift#1]
Hi,
when I call isToday i get "unrecognized selector sent to instance" because isDateInToday on NSCalendar is not implemented.

**Comment by kamilpowalowski** [comment]
My bad. Methods like isDateInToday are implemented in iOS 8.0

**Comment by harlanhaskins** [comment]
I went ahead and added `@availability()` qualifiers to all those functions.
