### ISSUE TITLE
Broken code example in readme

### ISSUE THREAD

**Issue by gambogi** [harlanhaskins/Punctual.swift#2]
The last example claims to get tomorrow's date:

``` swift
// get tomorrow's date
sleep(1.day.timeInterval)
print(NSDate())
```

This will work in most cases, unless completing the call to `1.day.timeInterval` takes longer than the remaining time in the day. The process will then sleep for a day, and print the date of the day _after_ tomorrow.

This is a critical issue with this code example.

**Comment by harlanhaskins** [comment]
Ah, yes! This code will break if run between `11:59:59.9999998` and `00:00:00.0`

**Comment by harlanhaskins** [comment]
I've removed the offending code. Thanks for the contribution!

**Comment by gambogi** [comment]
It also breaks on daylight savings and leap seconds actually.

**Comment by harlanhaskins** [comment]
Real talk: the correct version:

`1.day.fromNow`

Will properly handle Daylight Saving Time and leap seconds. Good ol' calendar APIs.

**Comment by gambogi** [comment]
Does that give you a time interval though?

**Comment by harlanhaskins** [comment]
The code example was made to get tomorrow's date by sleeping 1 full day and then getting the date.
The time interval was an implementation detail

**Comment by gambogi** [comment]
Oh I thought you were providing a riff on the `sleep` implementation.
