### ISSUE TITLE
example subdirectory is not excluded

### ISSUE THREAD

**Issue by mxcl** [harlanhaskins/Punctual.swift#3]
We have no way to exclude it yet, so I'll have to consider what should be done.

Anyway, currently it gets built and thus fails:

```
 swift build
Compiling Swift Module 'example' (2 sources)
/Users/mxcl/scratch/Punctual.swift/example/Package.swift:1:8: error: no such module 'PackageDescription'
import PackageDescription
       ^
/Users/mxcl/scratch/Punctual.swift/example/Package.swift:1:8: error: no such module 'PackageDescription'
import PackageDescription
       ^
<unknown>:0: error: build had 1 command failures
swift-build: exit(1): ["/Library/Developer/Toolchains/swift-2.2-SNAPSHOT-2015-12-01-a.xctoolchain/usr/bin/swift-build-tool", "-f", "/Users/mxcl/scratch/Punctual.swift/.build/debug/Punctual.o/llbuild.yaml"]
```

**Comment by harlanhaskins** [comment]
Oops! Yep, that's an issue. I'll just split it into another repo.

I think in the long term, it's probably a good idea to specify a directory for source files that defaults to `.`. 

We should also probably have some kind of default Pckage.swift template.

**Comment by harlanhaskins** [comment]
I removed it from this repository and re-did the tag. :+1: Thanks!
